authapp/urls.py
from django.urls import path, re_path

from authapp.views import register, login, logout, profile, send_verify_mail, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

from basketapp.views import basket_add, basket_edit, basket_remove

app_name = "basketapp"

urlpatterns = [
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-remove/<int:id>/', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('new-admin/', include('adminapp.urls', namespace='new_admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.db import models
from django.db.models.deletion import CASCADE

from authapp.models import User
from mainapp.models import Product


# Create your models here.


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    product = models.ForeignKey(Product, on_delete=CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Корзина пользователя: {self.user.username} | Товар: {self.product.name}"

    def sum(self):
        return self.quantity * self.product.price

    def total_quantity(self):
        user_products = Basket.objects.filter(user=self.user)
        return sum(
            user_product.quantity for user_product in user_products)

    def total_sum(self):
        user_products = Basket.objects.filter(user=self.user)
        return sum(user_product.sum() for user_product in user_products)

basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import HttpResponseRedirect
from django.template.loader import render_to_string

from basketapp.models import Basket
from mainapp.models import Product


@login_required
def basket_add(request, product_id=None):
    product = Product.objects.get(pk=product_id)
    basket = Basket.objects.filter(user=request.user, product=product)

    if not basket.exists():
        basket = Basket(user=request.user, product=product)
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = basket.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, id=None):
    basket = Basket.objects.get(id=id)
    basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, id, quantity):
    if request.is_ajax():
        user_product = Basket.objects.get(id=id)
        if quantity > 0:
            user_product.quantity = quantity
            user_product.save()
        else:
            user_product.delete()
        basket = Basket.objects.filter(user=request.user)
        context = {'basket': basket}
        result = render_to_string('basketapp/basket.html', context)
        return JsonResponse({'result': result})

basketapp/templates/basketapp/basket.html
<div class="basket_list">
    {% if basket %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ basket.0.total_quantity }}</span>
        </h4>
    {% else %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина Пуста</h4>
    {% endif %}

    {% for user_product in basket %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ user_product.product.name }}</h5>
                <p class="card-text">{{ user_product.product.short_description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="{{ user_product.id }}" type="number" class="form-control"
                                   value="{{ user_product.quantity }}"
                                   min="0">
                        </div>
                        <div class="col-lg-4">{{ user_product.sum }}</div>
                        <div class="col-lg-4">
                            <a href="{% url 'basket:basket_remove' user_product.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}

    {% if basket %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ basket.0.total_sum }} руб.</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
    {% endif %}
</div>