adminapp/urls.py
from django.urls import path

from adminapp.views import UserUpdateView, UserDeleteView, index, UserListView, UserCreateView, ProductCreateView, \
    ProductDeleteView, ProductUpdateView, ProductListView

app_name = 'adminapp'

urlpatterns = [
    path('', index, name='index'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='admin_users_delete'),
    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('product-create/', ProductCreateView.as_view(), name='admin_product_create'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='admin_product_update'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='admin_product_delete'),
    path('products/', ProductListView.as_view(), name='admin_products'),
]

authapp/urls.py
from django.urls import path, re_path

from authapp.views import register, login, logout, profile, send_verify_mail, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('new-admin/', include('adminapp.urls', namespace='new_admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adminapp/models.py
# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import ShopUserRegisterForm, ShopUserProfileForm
from authapp.models import User
from mainapp.models import Product


class NewAdminRegisterForm(ShopUserRegisterForm):
    avatar = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(NewAdminRegisterForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'


class NewAdminProfileForm(ShopUserProfileForm):
    avatar = forms.ImageField(widget=forms.FileInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(NewAdminProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = False
        self.fields['email'].widget.attrs['readonly'] = False


class ProductCreateForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'image':
                field.widget.attrs['class'] = 'custom-file-input'
            else:
                field.widget.attrs['class'] = 'form-control py-4'

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from adminapp.forms import NewAdminRegisterForm, NewAdminProfileForm, ProductCreateForm
from authapp.models import User
from mainapp.models import Product


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def index(request):
    return render(request, 'adminapp/admin.html')


class UserListView(ListView):
    model = User
    template_name = 'adminapp/admin-users-read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser, login_url='/'))
    def dispatch(self, request, *args, **kwargs):
        return super(UserListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['title'] = 'Список пользователей'
        return context


class UserCreateView(CreateView):
    model = User
    template_name = 'adminapp/admin-users-create.html'
    form_class = NewAdminRegisterForm
    success_url = reverse_lazy('new_admin:admin_users')

    def get_context_data(self, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание пользователя'
        return context


class UserUpdateView(UpdateView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    form_class = NewAdminProfileForm
    success_url = reverse_lazy('new_admin:admin_users')

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование пользователя'
        return context


class UserDeleteView(DeleteView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('new_admin:admin_users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/admin-product-read.html'


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/admin-product-create.html'
    form_class = ProductCreateForm
    success_url = reverse_lazy('new_admin:admin_products')


class ProductUpdateView(UpdateView):
    model = Product


class ProductDeleteView(DeleteView):
    model = Product

adminapp/templates/adminapp/admin-product-create.html
{% extends "adminapp/base.html" %}
{% load staticfiles %}
{% block content %}
    <h1 class="mt-4">Добавление Товара</h1>
    <form action="{% url 'new_admin:admin_product_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование Товара</label>
                    {{ form.name }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                    {{ form.category }}
                </div>
            </div>
        </div>
        <div class="form-row mb-2">
            <div class="col-lg-12">
                <div class="custom-file">
                    {{ form.image }}
                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                        изображение</label>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                {{ form.description }}
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.short_description.id_for_label }}">Краткое описание</label>
                {{ form.short_description }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                {{ form.quantity }}
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена за единицу</label>
                {{ form.price }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
    </form>
{% endblock content %}

adminapp/templates/adminapp/admin-product-read.html
{% extends "adminapp/base.html" %}
{% load staticfiles %}
{% block content %}
    <h1 class="mt-4">Товары</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Товары
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Название товара</th>
                        <th>Категория</th>
                        <th>Краткое описание</th>
                        <th>Кол-во</th>
                        <th>Цена за шт</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Название товара</th>
                        <th>Категория</th>
                        <th>Краткое описание</th>
                        <th>Кол-во</th>
                        <th>Цена за шт</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for product in object_list %}
                        <tr>
                            <td><a href="{% url 'new_admin:admin_product_update' product.id %}"
                                   style="color: dodgerblue">{{ product.name }}</a></td>
                            <td>{{ product.category.name }}</td>
                            <td>{{ product.short_description }}</td>
                            <td>{{ product.quantity }}</td>
                            <td>{{ product.price }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'new_admin:admin_product_create' %}">
                <button class="btn btn-success">Добавить Товар</button>
            </a>
        </div>
    </div>
{% endblock content %}

adminapp/templates/adminapp/admin-users-create.html
{% extends "adminapp/base.html" %}
{% load staticfiles %}
{% block content %}
    <h1 class="mt-4">Создание пользователя</h1>
    <form action="{% url 'new_admin:admin_users_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
            </div>
        </div>
        <div class="form-row mb-2">
            <div class="col-lg-12">
                <div class="custom-file">
                    {{ form.avatar }}
                    <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                        изображение</label>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                    почты</label>
                {{ form.email }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                {{ form.password1 }}
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                {{ form.password2 }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                {{ form.age }}
            </div>
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
    </form>
{% endblock content %}

adminapp/templates/adminapp/admin-users-read.html
{% extends "adminapp/base.html" %}
{% load staticfiles %}
{% block content %}
    <h1 class="mt-4">Пользователи</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Пользователи
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Адрес эл. почты</th>
                        <th>Персонал сайта</th>
                        <th>Активный</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Адрес эл. почты</th>
                        <th>Персонал сайта</th>
                        <th>Активный</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for user in object_list %}
                        <tr>
                            <td><a href="{% url 'new_admin:admin_users_update' user.id %}"
                                   style="color: dodgerblue">{{ user.username }}</a></td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.email }}</td>
                            <td class="text-center">
                                {% if user.is_staff or user.is_superuser %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if user.is_active %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'new_admin:admin_users_create' %}">
                <button class="btn btn-success">Создать пользователя</button>
            </a>
        </div>
    </div>
{% endblock content %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends "adminapp/base.html" %}
{% load staticfiles %}
{% block content %}
    <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
    <div class="card-body">
        <form action="{% url 'new_admin:admin_users_update' user.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">
                            {% if user.avatar %}
                                {{ media_url }}{{ user.avatar }}
                            {% else %}
                                Выберите
                                изображение</label>
                            {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                    {{ form.age }}
                </div>
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <form action="{% url 'new_admin:admin_users_delete' user.id %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

adminapp/templates/adminapp/admin.html
{% extends "adminapp/base.html" %}
{% load staticfiles %}
{% block content %}
    <h1 class="mt-4">Административная панель</h1>
{% endblock content %}

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title|title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href={% url 'main' %}>GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'new_admin:admin_users' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="#">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{% url 'new_admin:admin_products' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                {% block content %}

                {% endblock content %}
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2020</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>