authapp/urls.py
from django.urls import path, re_path

from authapp.views import register, login, logout, profile, send_verify_mail, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

from basketapp.views import basket_add, basket_edit, basket_remove

app_name = "basketapp"

urlpatterns = [
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-remove/<int:id>/', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('new-admin/', include('adminapp.urls', namespace='new_admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:category_id>/', mainapp.products, name='category'),
    path('page/<int:page_num>/', mainapp.products, name='page'),
]

mainapp/models.py
from django.db import models
from django.db.models.deletion import CASCADE


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='Название Категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория Продукта'
        verbose_name_plural = 'Категории Продуктов'
        ordering = ['name']


class Product(models.Model):
    name = models.CharField(
        verbose_name='Название Продукта', max_length=64, unique=True)
    category = models.ForeignKey(
        verbose_name='Категория', to=ProductCategory, on_delete=CASCADE)
    description = models.TextField(
        verbose_name='Описание Продукта', blank=True)
    short_description = models.CharField(
        verbose_name='Краткое Описание', max_length=64)
    price = models.DecimalField(
        verbose_name='Цена', decimal_places=2, max_digits=8, default=0)
    quantity = models.PositiveIntegerField(
        verbose_name='Количество', default=0)
    image = models.ImageField(
        verbose_name='Изображение', upload_to='products_images', blank=True)

    def __str__(self):
        return f'{self.category.name}:{self.name}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name']

mainapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from mainapp.models import Product, ProductCategory


def main(request):
    context = {
        'title': 'Главная'
    }
    return render(request, 'mainapp/index.html', context)


def products(request, category_id=None, page_num=1):
    context = {'title': 'Товары', 'categories': ProductCategory.objects.all()}
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()
    paginator = Paginator(products, per_page=3)
    products_paginator = paginator.page(page_num)
    context.update({'products': products_paginator})
    return render(request, 'mainapp/products.html', context)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block title %}
            {{ title | title }}
        {% endblock title %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">

    {% block css %}
    {% endblock css %}

    {% block js %}
    {% endblock js %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-shopping-bag"></i></a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:profile' %}">{{ user.username }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    {% if user.is_superuser or user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'new_admin:index' %}">
                                <i class="fab fa-dev"></i>
                            </a>
                        </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:logout' %}">Выйти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock content %}

{% block footer %}
{% endblock footer %}

<!-- Bootstrap core JavaScript -->
<script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static '/vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/basket.js' %}"></script>
</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block css %}
    <link href="{% static '/css/index.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <!-- Page Content -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <p>
                        {% now "jS F Y H:i" %}
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block css %}
    <link href="{% static '/css/products.css' %} " rel="stylesheet">
{% endblock css %}


{% block content %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}"
                           class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>
            <!-- /.col-lg-3 -->
            <div class="col-lg-9">
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static '/vendor/img/slides/slide-1.jpg' %} "
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static '/vendor/img/slides/slide-2.jpg' %} "
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static '/vendor/img/slides/slide-3.jpg' %} "
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top" src="/media/{{ product.image }}"
                                         alt="{{ product.short_description }}">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб</h5>
                                    <p class="card-text">{{ product.short_description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'basket:basket_add' product.id %}">
                                        <button type="button" class="btn btn-outline-success">Отправить в корзину
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_previous %} {% url 'products:page' products.previous_page_number %} {% else %} # {% endif %}"
                               tabindex="-1"
                               aria-disabled="true">
                                Previous
                            </a>
                        </li>
                        {% for page in products.paginator.page_range %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'products:page' page %}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_next %} {% url 'products:page' products.next_page_number %} {% else %} # {% endif %}">
                                Next
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- /.container -->
{% endblock content %}


{% block footer %}
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop {% now 'Y' %}</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock footer %}